<?xml version="1.0"?>

<robot name="barebones" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- - - - - - - - - - - conventions - - - - - - - - - - -->

  <!-- width goes left to right (y-axis) -->
  <!-- length is front to back (x-axis) -->
  <!-- height is up down (z-axis) --> 
  
  <!-- reflection convention -->
  <!-- 
  front +1 
  back  -1 
  left  +1 
  right -1 
  -->

  <!-- - - - - - - - - - dimensions, mass, and parameters - - - - - - - - - -->

  <!-- <xacro:property name="chassis_length" value="3.38"/>
  <xacro:property name="chassis_width" value="0.92"/>
  <xacro:property name="chassis_height" value="1.4"/>
  <xacro:property name="chassis_mass" value="4"/> -->
  <xacro:property name="chassis_length" value="0.258"/>
  <xacro:property name="chassis_width" value="0.168"/>
  <xacro:property name="chassis_height" value="0.02"/>
  <xacro:property name="chassis_mass" value="2.788"/>

  <!-- tire interia is a hollow cylinder, hence hub_dia -->
  <!-- <xacro:property name="tire_dia" value="${0.575*2}"/>
  <xacro:property name="hub_dia" value="${tire_dia/1.5}"/>
  <xacro:property name="tire_width" value="${tire_dia/3.0}"/>
  <xacro:property name="wheel_mass" value="1"/> -->
  <xacro:property name="tire_dia" value="0.14605"/>
  <xacro:property name="hub_dia" value="${tire_dia/1.5}"/>
  <xacro:property name="tire_width" value="${tire_dia/3.0}"/>
  <xacro:property name="wheel_mass" value="0.29"/>

  <!-- tire left/right and front/rear separation -->
  <xacro:property name="tire_lr_separation" value="2.36"/>
  <xacro:property name="tire_fr_separation" value="5.216"/>
  <xacro:property name="tire_z_offset" value="${chassis_height/2+0.614}"/>
  
  <!-- tire parameters -->
  <xacro:property name="tire_effort" value="100"/>
  <xacro:property name="tire_velocity" value="100"/>
  <xacro:property name="tire_mu1" value="1"/>
  <xacro:property name="tire_mu2" value="1"/>
  <xacro:property name="tire_kp" value="${1e9}"/>
  <xacro:property name="tire_kd" value="${5e6}"/>
  <!-- <xacro:property name="tire_minDepth" value="0.005"/> -->

  <!-- steeriing parameters -->
  <xacro:property name="steeriing_effort" value="10000000"/>
  <xacro:property name="steeriing_lower" value="${-pi/4}"/>
  <xacro:property name="steeriing_upper" value="${pi/4}"/>
  <xacro:property name="steeriing_velocity" value="10000000"/>


  
  <!-- - - - - - - - - - - Inertia Macros - - - - - - - - - - -->
  
  <!-- Null -->
  <xacro:macro name="null_inertial">
    <inertial>
      <mass value="0.001"/>
      <inertia ixx="0.00001" ixy="0" ixz="0" iyy="0.00001" iyz="0" izz="0.00001"/>
    </inertial>
  </xacro:macro>
  
  <!-- solid cuboid -->
  <xacro:macro name="solid_cuboid_inertial"
               params="width depth height mass *origin">
    <inertial>
      <xacro:insert_block name="origin"/>
      <mass value="${mass}"/>
      <inertia ixx="${mass * (depth * depth + height * height) / 12}"
               ixy="0" ixz="0"
               iyy="${mass * (width * width + height * height) / 12}"
               iyz="0"
               izz="${mass * (width * width + depth * depth) / 12}"/>
    </inertial>
  </xacro:macro>
  
  <!-- thick-walled cylindrical tube with open ends -->
  <xacro:macro name="thick_walled_tube_inertial"
               params="inner_rad outer_rad height mass">
    <inertial>
      <mass value="${mass}"/>
      <inertia ixx="${(1 / 12) * mass * (3 * (inner_rad * inner_rad +
                    outer_rad * outer_rad) + height * height)}"
               ixy="0" ixz="0"
               iyy="${(1 / 12) * mass * (3 * (inner_rad * inner_rad +
                    outer_rad * outer_rad) + height * height)}"
               iyz="0"
               izz="${mass * (inner_rad * inner_rad +
                    outer_rad * outer_rad) / 2}"/>
    </inertial>
  </xacro:macro>
  
  <!-- - - - - - - - - - - colors - - - - - - - - - - -->
  
  <material name="chassis_mat">
    <color rgba="0.5 0.5 0.5 1"/>
  </material>

  <material name="tire_mat">
    <color rgba="0 0 0 1"/>
  </material>
  
  
  <!-- - - - - - - - - - - base_link - - - - - - - - - - -->

  <link name="base_link"/>

  <!-- chassis -->
  <link name="chassis">
    <visual>
      <origin xyz="0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <material name="chassis_mat"/>
    </visual>
    <collision>
      <origin xyz="0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>
    <xacro:solid_cuboid_inertial
        width="${chassis_length}" depth="${chassis_width}"
        height="${chassis_height}" mass="${chassis_mass}">
      <origin xyz="0 0 0"/>
    </xacro:solid_cuboid_inertial>
  </link>
  <joint name="base_link_to_chasis" type="fixed">
    <parent link="base_link"/>
    <child link="chassis"/>
    <origin xyz="0 0 ${tire_dia/2+tire_z_offset}"/>
  </joint>
  <gazebo reference="chassis">
    <material>Gazebo/White</material>
  </gazebo>

  <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
  <!-- FRONT -->

  <!-- axel_carrier -->
  <!-- left -->
  <xacro:macro name="front_axle_carrier" params="lr_prefix lr_reflect">
    <link name="${lr_prefix}_front_axle_carrier">
        <xacro:null_inertial/>
    </link>
    <joint name="${lr_prefix}_steering_joint" type="revolute">
        <parent link="chassis"/>
        <child link="${lr_prefix}_front_axle_carrier"/>
        <origin xyz="${tire_fr_separation/2} ${lr_reflect*tire_lr_separation/2} ${-tire_z_offset}"/>
        <axis xyz="0 0 1"/>
        <limit effort="${steeriing_effort}" lower="${steeriing_lower}" upper="${steeriing_upper}" velocity="${steeriing_velocity}"/>
    </joint>
    <transmission name="${lr_prefix}_steering_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="${lr_prefix}_steering_joint">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="${lr_prefix}_steering_act">
        <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>
  </xacro:macro>
  <xacro:front_axle_carrier lr_prefix="left" lr_reflect="1"/>
  <xacro:front_axle_carrier lr_prefix="right" lr_reflect="-1"/>  

  <!-- wheel -->
  <xacro:macro name="front_wheel" params="lr_prefix lr_reflect">
    <link name="${lr_prefix}_front_wheel">
      <visual>
        <origin xyz="0 0 0"/>
        <geometry>
        <cylinder length="${tire_width}" radius="${tire_dia/2}"/>
        </geometry>
        <material name="tire_mat"/>
      </visual>
      <collision>
        <origin xyz="0 0 0"/>
        <geometry>
        <cylinder length="${tire_width}" radius="${tire_dia/2}"/>
        </geometry>
      </collision>
      <xacro:thick_walled_tube_inertial
        inner_rad="${hub_dia/2}" outer_rad="${tire_dia/2}"
        height="${tire_width}" mass="${wheel_mass}"/>
    </link>
    <joint name="${lr_prefix}_front_axle" type="continuous">
        <parent link="${lr_prefix}_front_axle_carrier"/>
        <child link="${lr_prefix}_front_wheel"/>
        <origin rpy="${pi/2} 0 0"/>
        <axis xyz="0 0 -1"/>
        <limit effort="${tire_effort}" velocity="${tire_velocity}"/>
    </joint>
    <transmission name="${lr_prefix}_front_axle_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="${lr_prefix}_front_axle">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="${lr_prefix}_front_axle_act">
        <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>
    <gazebo reference="${lr_prefix}_front_wheel">
        <mu1 value="${tire_mu1}"/>
        <mu2 value="${tire_mu2}"/>
        <kp value="${tire_kp}"/>
        <kd value="${tire_kd}"/>
        <!-- <minDepth value="${tire_minDepth}"/> -->
        <material>Gazebo/Black</material>
    </gazebo>
  </xacro:macro>
  <xacro:front_wheel lr_prefix="left" lr_reflect="1"/>
  <xacro:front_wheel lr_prefix="right" lr_reflect="-1"/>  


  <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
  <!-- REAR -->
  <xacro:macro name="rear_tires" params="lr_prefix lr_reflect">
    <link name="${lr_prefix}_rear_wheel">
      <visual>
        <origin xyz="0 0 0"/>
        <geometry>
          <cylinder length="${tire_width}" radius="${tire_dia/2}"/>
        </geometry>
        <material name="tire_mat"/>
      </visual>
      <collision>
        <origin xyz="0 0 0"/>
        <geometry>
          <cylinder length="${tire_width}" radius="${tire_dia/2}"/>
        </geometry>
      </collision>
      <xacro:thick_walled_tube_inertial
            inner_rad="${hub_dia/2}" outer_rad="${tire_dia/2}"
            height="${tire_width}" mass="${wheel_mass}"/>
    </link>
    <joint name="${lr_prefix}_rear_axle" type="continuous">
        <parent link="chassis"/>
        <child link="${lr_prefix}_rear_wheel"/>
        <origin xyz="${-tire_fr_separation/2} ${lr_reflect*tire_lr_separation/2} ${-tire_z_offset}" rpy="${pi/2} 0 0"/>
        <axis xyz="0 0 -1"/>
        <limit effort="${tire_effort}" velocity="${tire_velocity}"/>
    </joint>
    <transmission name="${lr_prefix}_rear_axle_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="${lr_prefix}_rear_axle">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="${lr_prefix}_rear_axle_act">
        <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>
    <gazebo reference="${lr_prefix}_rear_wheel">
        <mu1 value="${tire_mu1}"/>
        <mu2 value="${tire_mu2}"/>
        <kp value="${tire_kp}"/>
        <kd value="${tire_kd}"/>
        <!-- <minDepth value="${tire_minDepth}"/> -->
        <material>Gazebo/Black</material>
    </gazebo>
  </xacro:macro>
  <xacro:rear_tires lr_prefix="left" lr_reflect="1"/>
  <xacro:rear_tires lr_prefix="right" lr_reflect="-1"/>  

  <!-- gazebo plugins for control and odometry ground truth-->
  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so" />
    <plugin name="gazebo_ros_p3d"     filename="libgazebo_ros_p3d.so">
      <frameName>map</frameName>
      <bodyName>base_link</bodyName>
      <topicName>odom_truth</topicName>
      <updateRate>30.0</updateRate>
    </plugin>
  </gazebo>

</robot>
